name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'     
        required: true
        default: 'latest'
env:
  TAG: ghcr.io/${{ github.repository }}:latest

jobs:

  push-and-tag:
    name: Deploy containers to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Container amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          load: true
          tags: ${{ env.TAG }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Container amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          platforms: linux/amd64